package views;

import conexao.Conexao;
import data.Agendamentos;
import data.AgendamentosDao;
import data.Usuarios;
import data.UsuariosDao;
import java.sql.Connection;
import java.util.List;
import javax.swing.table.DefaultTableModel;


/**
 *
 * @author lucas
 */
public class TelaInicial extends javax.swing.JFrame {
    
    private void preencheTabela(){
        AgendamentosDao agendDao = new AgendamentosDao();
        
        List<Agendamentos> listaAgendamentos = agendDao.listaAgendamentos();
        DefaultTableModel tableAgendamentos = (DefaultTableModel) tblInicial.getModel();
        tableAgendamentos.setNumRows(0);
        
        for(Agendamentos a: listaAgendamentos){
            Object[] obj = new Object[]{
                a.getId(),
                a.getDataAgendamento(),
                a.getServico().getNome(),
                a.getFuncionario().getNome(),
                a.getCliente().getNome(),
                a.getTipoPagamento()
            };
            tableAgendamentos.addRow(obj);
            agendDao.listaAgendamentos();
        }
    }
    
    public void botaoFuncDesabilitado(){
        botaoFuncionarios.setEnabled(false);
    }
    
    public void botaoServDesabilitado(){
        botaoServico.setEnabled(false);
    }
    
    public void buscaLogin(String nome){
        lblUsu.setText(nome);
    }

    /**
     * Creates new form TelaI
     */
    public TelaInicial() {
        initComponents();
        this.setLocationRelativeTo(null);
        TelaAgendamentoCad telaA = new TelaAgendamentoCad();
        preencheTabela();
        TelaLogin telaL = new TelaLogin();
        if(telaL.tipoUsuario() == "funcionario"){
            botaoFuncDesabilitado();
            botaoServDesabilitado();
        }
        lblUsu.setText(TelaLogin.nomeUsuario());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        botaoAgendamentos = new javax.swing.JButton();
        botaoClientes = new javax.swing.JButton();
        botaoFuncionarios = new javax.swing.JButton();
        botaoServico = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        botaoSair = new javax.swing.JButton();
        lblUsu = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblInicial = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("BARBERSHOPINICIAL");

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setPreferredSize(new java.awt.Dimension(950, 680));
        jPanel1.setLayout(null);

        jPanel2.setBackground(new java.awt.Color(24, 9, 0));

        botaoAgendamentos.setBackground(new java.awt.Color(172, 137, 82));
        botaoAgendamentos.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        botaoAgendamentos.setForeground(new java.awt.Color(255, 255, 255));
        botaoAgendamentos.setText("Agendamentos");
        botaoAgendamentos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoAgendamentosActionPerformed(evt);
            }
        });

        botaoClientes.setBackground(new java.awt.Color(172, 137, 82));
        botaoClientes.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        botaoClientes.setForeground(new java.awt.Color(255, 255, 255));
        botaoClientes.setText("Clientes");
        botaoClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoClientesActionPerformed(evt);
            }
        });

        botaoFuncionarios.setBackground(new java.awt.Color(172, 137, 82));
        botaoFuncionarios.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        botaoFuncionarios.setForeground(new java.awt.Color(255, 255, 255));
        botaoFuncionarios.setText("Funcionários");
        botaoFuncionarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoFuncionariosActionPerformed(evt);
            }
        });

        botaoServico.setBackground(new java.awt.Color(172, 137, 82));
        botaoServico.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        botaoServico.setForeground(new java.awt.Color(255, 255, 255));
        botaoServico.setText("Serviços");
        botaoServico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoServicoActionPerformed(evt);
            }
        });

        jButton6.setBackground(new java.awt.Color(172, 137, 82));
        jButton6.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jButton6.setForeground(new java.awt.Color(255, 255, 255));
        jButton6.setText("CALENDÁRIO");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(18, Short.MAX_VALUE)
                .addComponent(botaoAgendamentos, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(botaoClientes, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(botaoFuncionarios, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(botaoServico, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botaoAgendamentos, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botaoClientes, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botaoFuncionarios, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botaoServico, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(30, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel2);
        jPanel2.setBounds(0, 0, 950, 100);

        jPanel3.setBackground(new java.awt.Color(216, 184, 135));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/test3.png"))); // NOI18N

        botaoSair.setBackground(new java.awt.Color(24, 9, 0));
        botaoSair.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        botaoSair.setForeground(new java.awt.Color(255, 255, 255));
        botaoSair.setText("Sair");
        botaoSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoSairActionPerformed(evt);
            }
        });

        lblUsu.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        lblUsu.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(botaoSair, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addContainerGap(24, Short.MAX_VALUE))
            .addComponent(lblUsu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(jLabel1)
                .addGap(71, 71, 71)
                .addComponent(lblUsu)
                .addGap(18, 18, 18)
                .addComponent(botaoSair, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(159, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel3);
        jPanel3.setBounds(0, 100, 180, 580);

        tblInicial.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Data", "Serviço", "Funcionário", "Cliente", "TipoPagamento"
            }
        ));
        jScrollPane1.setViewportView(tblInicial);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(192, 112, 750, 560);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botaoAgendamentosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoAgendamentosActionPerformed
        TelaAgendamentoCad telaAgend = new TelaAgendamentoCad();
        telaAgend.setVisible(true);
        dispose();
    }//GEN-LAST:event_botaoAgendamentosActionPerformed

    private void botaoClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoClientesActionPerformed
        TelaClientesCad telaCli = new TelaClientesCad();
        telaCli.setVisible(true);
        dispose();
    }//GEN-LAST:event_botaoClientesActionPerformed

    private void botaoFuncionariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoFuncionariosActionPerformed
        TelaFuncionarioCad telaFunc = new TelaFuncionarioCad();
        telaFunc.setVisible(true);
        dispose();
    }//GEN-LAST:event_botaoFuncionariosActionPerformed

    private void botaoServicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoServicoActionPerformed
        TelaServicos telaS = new TelaServicos();
        telaS.setVisible(true);
        dispose();
    }//GEN-LAST:event_botaoServicoActionPerformed

    private void botaoSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoSairActionPerformed
        TelaLogin telal = new TelaLogin();
        telal.setVisible(true);
        dispose();
    }//GEN-LAST:event_botaoSairActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaInicial().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botaoAgendamentos;
    private javax.swing.JButton botaoClientes;
    private javax.swing.JButton botaoFuncionarios;
    private javax.swing.JButton botaoSair;
    private javax.swing.JButton botaoServico;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblUsu;
    private javax.swing.JTable tblInicial;
    // End of variables declaration//GEN-END:variables


}
