package views;

import conexao.Conexao;
import data.Agendamentos;
import data.AgendamentosDao;
import data.Clientes;
import data.ClientesDao;
import data.Funcionarios;
import data.FuncionariosDao;
import data.Servicos;
import data.ServicosDao;
import static java.awt.image.ImageObserver.WIDTH;
import java.sql.SQLException;
import java.text.DateFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author lucas
 */
public class TelaAgendamentoCad extends javax.swing.JFrame { 
    
    private void preencheTabela(){
        AgendamentosDao agendDao = new AgendamentosDao();
        
        List<Agendamentos> listaAgendamentos = agendDao.listaAgendamentos();
        DefaultTableModel tableAgendamentos = (DefaultTableModel) tblAgendamentos.getModel();
        tableAgendamentos.setNumRows(0);
        
        for(Agendamentos a: listaAgendamentos){
            Object[] obj = new Object[]{
                a.getId(),
                a.getDataAgendamento(),
                a.getServico().getNome(),
                a.getFuncionario().getNome(),
                a.getCliente().getNome(),
                a.getTipoPagamento()
            };
            tableAgendamentos.addRow(obj);
            agendDao.listaAgendamentos();
        }
    }
    /**
     * Creates new form TelaAgendamento
     */
    public TelaAgendamentoCad() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setTitle("AGENDAMENTOS");
        jLayeredPane1.setOpaque(rootPaneCheckingEnabled);
        preencheTabela();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLayeredPane1 = new javax.swing.JLayeredPane();
        lblTitulo = new javax.swing.JLabel();
        txtServico = new javax.swing.JTextField();
        txtDataHora = new javax.swing.JTextField();
        txtCliente = new javax.swing.JTextField();
        txtFuncionario = new javax.swing.JTextField();
        botaoAgendar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblAgendamentos = new javax.swing.JTable();
        botaoVoltar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtBuscaNome = new javax.swing.JTextField();
        botaoBuscar = new javax.swing.JButton();
        botaoAtualizar = new javax.swing.JButton();
        botaoExcluir = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        btnCli = new javax.swing.JButton();
        txtPagamento = new javax.swing.JTextField();
        lblTipoPag = new javax.swing.JLabel();
        btnFuncionarios = new javax.swing.JButton();
        btnServicos = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLayeredPane1.setBackground(new java.awt.Color(24, 9, 0));
        jLayeredPane1.setForeground(new java.awt.Color(24, 9, 0));

        lblTitulo.setFont(new java.awt.Font("Segoe UI", 0, 30)); // NOI18N
        lblTitulo.setForeground(new java.awt.Color(255, 255, 255));
        lblTitulo.setText("Cadastrar Agendamento");

        botaoAgendar.setBackground(new java.awt.Color(172, 137, 82));
        botaoAgendar.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        botaoAgendar.setForeground(new java.awt.Color(255, 255, 255));
        botaoAgendar.setText("Agendar");
        botaoAgendar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoAgendarActionPerformed(evt);
            }
        });

        tblAgendamentos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Data", "Serviço", "Funcionário", "Cliente", "Tipo de pagamento"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblAgendamentos);

        botaoVoltar.setBackground(new java.awt.Color(172, 137, 82));
        botaoVoltar.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        botaoVoltar.setForeground(new java.awt.Color(255, 255, 255));
        botaoVoltar.setText("<");
        botaoVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoVoltarActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 25)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Agendamentos");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Buscar por ID:");

        botaoBuscar.setBackground(new java.awt.Color(172, 137, 82));
        botaoBuscar.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        botaoBuscar.setForeground(new java.awt.Color(255, 255, 255));
        botaoBuscar.setText("Buscar");
        botaoBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoBuscarActionPerformed(evt);
            }
        });

        botaoAtualizar.setBackground(new java.awt.Color(172, 137, 82));
        botaoAtualizar.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        botaoAtualizar.setForeground(new java.awt.Color(255, 255, 255));
        botaoAtualizar.setText("Atualizar");
        botaoAtualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoAtualizarActionPerformed(evt);
            }
        });

        botaoExcluir.setBackground(new java.awt.Color(172, 137, 82));
        botaoExcluir.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        botaoExcluir.setForeground(new java.awt.Color(255, 255, 255));
        botaoExcluir.setText("Excluir");
        botaoExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoExcluirActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Serviço ID");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Data/Hora");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Funcionário ID");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Cliente ID");

        btnCli.setBackground(new java.awt.Color(172, 137, 82));
        btnCli.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        btnCli.setForeground(new java.awt.Color(255, 255, 255));
        btnCli.setText("clientes");
        btnCli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCliActionPerformed(evt);
            }
        });

        lblTipoPag.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        lblTipoPag.setForeground(new java.awt.Color(255, 255, 255));
        lblTipoPag.setText("Tipo de pagamento");

        btnFuncionarios.setBackground(new java.awt.Color(172, 137, 82));
        btnFuncionarios.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        btnFuncionarios.setForeground(new java.awt.Color(255, 255, 255));
        btnFuncionarios.setText("Funcionários");
        btnFuncionarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFuncionariosActionPerformed(evt);
            }
        });

        btnServicos.setBackground(new java.awt.Color(172, 137, 82));
        btnServicos.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        btnServicos.setForeground(new java.awt.Color(255, 255, 255));
        btnServicos.setText("Serviços");
        btnServicos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnServicosActionPerformed(evt);
            }
        });

        jLayeredPane1.setLayer(lblTitulo, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(txtServico, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(txtDataHora, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(txtCliente, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(txtFuncionario, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(botaoAgendar, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jScrollPane1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(botaoVoltar, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jLabel2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jLabel3, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(txtBuscaNome, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(botaoBuscar, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(botaoAtualizar, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(botaoExcluir, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jLabel4, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jLabel5, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jLabel7, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jLabel6, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(btnCli, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(txtPagamento, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(lblTipoPag, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(btnFuncionarios, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(btnServicos, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jLayeredPane1Layout = new javax.swing.GroupLayout(jLayeredPane1);
        jLayeredPane1.setLayout(jLayeredPane1Layout);
        jLayeredPane1Layout.setHorizontalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jLayeredPane1Layout.createSequentialGroup()
                        .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                                .addGap(68, 68, 68)
                                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(txtServico, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtDataHora, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addComponent(jLabel4)
                                        .addComponent(jLabel5))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(lblTipoPag)
                                        .addComponent(txtPagamento, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jLayeredPane1Layout.createSequentialGroup()
                                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel6)
                                    .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(botaoAgendar, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(txtFuncionario)
                                            .addComponent(txtCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGap(37, 37, 37))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jLayeredPane1Layout.createSequentialGroup()
                                .addComponent(btnCli)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnFuncionarios)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnServicos))))
                    .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jLayeredPane1Layout.createSequentialGroup()
                            .addComponent(botaoVoltar, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblTitulo)
                            .addGap(246, 246, 246))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jLayeredPane1Layout.createSequentialGroup()
                            .addComponent(jLabel3)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(txtBuscaNome, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(botaoBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(botaoAtualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(botaoExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 893, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(29, Short.MAX_VALUE))
        );
        jLayeredPane1Layout.setVerticalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblTitulo)
                    .addComponent(botaoVoltar, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jLayeredPane1Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(21, 21, 21)
                        .addComponent(botaoAgendar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jLayeredPane1Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtServico, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(21, 21, 21)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtDataHora, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lblTipoPag)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtPagamento, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                        .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(btnCli)
                            .addComponent(btnFuncionarios)
                            .addComponent(btnServicos))
                        .addGap(7, 7, 7)))
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16)
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(botaoBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(botaoAtualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(botaoExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(txtBuscaNome, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLayeredPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLayeredPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCliActionPerformed
        TelaClientesCad telaCli = new TelaClientesCad();
        telaCli.setVisible(true);
    }//GEN-LAST:event_btnCliActionPerformed

    private void botaoExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoExcluirActionPerformed
        if(!emptyId()){
            int id = Integer.parseInt(txtBuscaNome.getText());
            AgendamentosDao agendDao = new AgendamentosDao();
            agendDao.excluir(id);
            JOptionPane.showMessageDialog(this, "Dados excluidos.");
            
            txtServico.setText("");
            txtDataHora.setText("");
            txtPagamento.setText("");
            txtCliente.setText("");
            txtFuncionario.setText("");
            
            preencheTabela();
        }
    }//GEN-LAST:event_botaoExcluirActionPerformed

    private void botaoVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoVoltarActionPerformed
        TelaInicial telaIni = new TelaInicial();
        telaIni.setVisible(true);
        dispose();
    }//GEN-LAST:event_botaoVoltarActionPerformed

    private void botaoAgendarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoAgendarActionPerformed
        Agendamentos agend = new Agendamentos();
        AgendamentosDao agendDao = new AgendamentosDao();
        Conexao con = new Conexao();
        
        if(valida()){
            if(!emptyFields()){
                con.getConection();
                try{
                    if(con.getConection().isClosed()){
                        JOptionPane.showMessageDialog(this, "Falha ao conectar a banco de dados");
                    }else{
                        try{

                            agend.setDataAgendamento(txtDataHora.getText());
                            
                            //SERVICO
                            int sId = Integer.parseInt(txtServico.getText());
                            ServicosDao servDao = new ServicosDao();
                            Servicos serv = servDao.buscaServicoPorId(sId);
                              if (serv == null) {
                                JOptionPane.showMessageDialog(this, "Serviço não encontrado: " + sId);

                            }else{
                                agend.setServico(serv);
                            }
                            
                            //CLIENTE
                            int cId = Integer.parseInt(txtCliente.getText());
                            ClientesDao cliDao = new ClientesDao();
                            Clientes cli = cliDao.buscaClientePorId(cId);
                              if (cli == null) {
                                JOptionPane.showMessageDialog(this, "Cliente não encontrado: " + cId);

                              }else{
                                  agend.setCliente(cli);
                              }

                            //FUNCIONARIO
                            int fId = Integer.parseInt(txtFuncionario.getText());
                            FuncionariosDao funcDao = new FuncionariosDao();
                            Funcionarios func = funcDao.buscaFuncionarioPorId(fId);
                              if (func == null) {
                                JOptionPane.showMessageDialog(this, "Funcionario não encontrado: " + fId);

                              }else{
                                  agend.setFuncionario(func);
                              }
                              
                              if(serv == null || cli == null || func == null){
                                  JOptionPane.showMessageDialog(this, "Falha ao cadastrar agendamento");
                              }else{
                                agend.setTipoPagamento(txtPagamento.getText());
                                agendDao.salvar(agend); 
                                JOptionPane.showMessageDialog(this, "Dados salvos com sucesso.");
                                preencheTabela(); 
                                txtServico.setText("");
                                txtDataHora.setText("");
                                txtPagamento.setText("");
                                txtCliente.setText("");
                                txtFuncionario.setText("");
                                txtServico.requestFocus();   

                                con.desconnect();
                              }
                        }catch(NumberFormatException e){
                            System.out.println("Error: "+ e.getMessage());
                        }
                    }
                }catch(SQLException e){
                    System.out.println("Erro: "+ e.getMessage());
                }
            }
        }
    }//GEN-LAST:event_botaoAgendarActionPerformed

    private void botaoAtualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoAtualizarActionPerformed
       try{
            if(!emptyId()){
               int id = Integer.parseInt(txtBuscaNome.getText());
               
               String data = txtDataHora.getText();
               
               int sId = Integer.parseInt(txtServico.getText());
               ServicosDao servDao = new ServicosDao();
               Servicos serv = servDao.buscaServicoPorId(sId);
               
               int cId = Integer.parseInt(txtCliente.getText());
               ClientesDao cliDao = new ClientesDao();
               Clientes cli = cliDao.buscaClientePorId(cId);
               
               int fId = Integer.parseInt(txtFuncionario.getText());
               FuncionariosDao funcDao = new FuncionariosDao();
               Funcionarios func = funcDao.buscaFuncionarioPorId(fId);
               
               String tipoPagamento = txtPagamento.getText();

               Agendamentos agend = new Agendamentos();

               agend.setServico(serv);
               agend.setDataAgendamento(data);
               agend.setTipoPagamento(tipoPagamento);
               agend.setCliente(cli);
               agend.setFuncionario(func);
               agend.setId(id);

               AgendamentosDao agendDao = new AgendamentosDao();
               agendDao.atualizar(agend);
               JOptionPane.showMessageDialog(this, "Dados atualizados com sucesso.");

                txtServico.setText("");
                txtDataHora.setText("");
                txtPagamento.setText("");
                txtCliente.setText("");
                txtFuncionario.setText("");
                txtServico.requestFocus(); 
                preencheTabela();
            }
       }catch(NumberFormatException e){
           System.out.println("Erro: "+ e.getMessage());
       }    
    }//GEN-LAST:event_botaoAtualizarActionPerformed

    private void botaoBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoBuscarActionPerformed
        if(!emptyId()){
            int id = Integer.parseInt(txtBuscaNome.getText());
            AgendamentosDao agendDao = new AgendamentosDao();
            Agendamentos agend = agendDao.getAgendamentos(id);
            
            if(agend == null){
                JOptionPane.showMessageDialog(this, "Agendamento não encontrado.");
            }else{
                txtServico.setText(String.valueOf(agend.getServico().getId()));
                txtDataHora.setText(agend.getDataAgendamento());
                txtPagamento.setText(agend.getTipoPagamento());
                txtCliente.setText(String.valueOf(agend.getCliente().getId()));
                txtFuncionario.setText(String.valueOf(agend.getFuncionario().getId()));
                preencheTabela();
            }
        }
    }//GEN-LAST:event_botaoBuscarActionPerformed

    private void btnFuncionariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFuncionariosActionPerformed
        TelaFuncionarioCad telaF = new TelaFuncionarioCad();
        telaF.setVisible(true);
    }//GEN-LAST:event_btnFuncionariosActionPerformed

    private void btnServicosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnServicosActionPerformed
        TelaServicos telaS = new TelaServicos();
        telaS.setVisible(true);
    }//GEN-LAST:event_btnServicosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaAgendamentoCad.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaAgendamentoCad.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaAgendamentoCad.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaAgendamentoCad.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaAgendamentoCad().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botaoAgendar;
    private javax.swing.JButton botaoAtualizar;
    private javax.swing.JButton botaoBuscar;
    private javax.swing.JButton botaoExcluir;
    private javax.swing.JButton botaoVoltar;
    private javax.swing.JButton btnCli;
    private javax.swing.JButton btnFuncionarios;
    private javax.swing.JButton btnServicos;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblTipoPag;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JTable tblAgendamentos;
    private javax.swing.JTextField txtBuscaNome;
    private javax.swing.JTextField txtCliente;
    private javax.swing.JTextField txtDataHora;
    private javax.swing.JTextField txtFuncionario;
    private javax.swing.JTextField txtPagamento;
    private javax.swing.JTextField txtServico;
    // End of variables declaration//GEN-END:variables
    
    public boolean emptyFields(){
        boolean isEmpty = true;
        if(txtServico.getText().trim().isEmpty() || txtCliente.getText().trim().isEmpty() || txtDataHora.getText().trim().isEmpty() || txtFuncionario.getText().trim().isEmpty() || txtPagamento.getText().trim().isEmpty()){
            JOptionPane.showMessageDialog(rootPane, "Preencha todos os campos para cadastrar");
        }else{
            isEmpty = false;
        }
        return isEmpty;
    }
    
    public boolean valida(){
        boolean valido = true;

        String data = txtDataHora.getText();

        boolean validaData = data.matches("[0-9]{2}[/][0-9]{2}[/][0-9]{4}[-][0-9]{2}[:][0-9]{2}");

        if(validaData == false){
            JOptionPane.showMessageDialog(rootPane, "Data/Hora inválida \nFormato(xx/xx/xxxx-xx:xx)");
            valido = false;
        }
        return valido;
    }

    public boolean emptyId(){
        boolean isEmpty = true;
        if(txtBuscaNome.getText().trim().isEmpty()){
            JOptionPane.showMessageDialog(rootPane, "Digite o ID antes de atualizar");
        }else{
            isEmpty = false;
        }
        return isEmpty;
    }
  
    public int pegaPosicao(){
        int posicao = tblAgendamentos.getSelectedRow();
        if(posicao == -1){
            JOptionPane.showMessageDialog(rootPane, "Selecione uma linha");
        }
        return posicao;
    }

}
